
import static java.lang.Math.toIntExact;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Monica BP
 */
public class Penitipan extends javax.swing.JFrame {

    private int totalhari;
    private int klr1;
    private int msk1;
    private int hargatotal;

    /**
     * Creates new form Penitipan
     */
    public Penitipan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        petugas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        resi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        masuk = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        keluar = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        mtr = new javax.swing.JRadioButton();
        mbl = new javax.swing.JRadioButton();
        Save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        hitung = new javax.swing.JButton();
        harga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Nama Petugas");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 240, 87, 15);

        petugas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasActionPerformed(evt);
            }
        });
        getContentPane().add(petugas);
        petugas.setBounds(40, 260, 210, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("No. Resi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 180, 49, 15);

        resi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(resi);
        resi.setBounds(40, 200, 210, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("No. Polisi");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 360, 55, 15);

        nopol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(nopol);
        nopol.setBounds(40, 380, 210, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Tanggal Masuk");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 420, 91, 15);

        masuk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(masuk);
        masuk.setBounds(40, 440, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Tanggal Keluar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 480, 90, 15);

        keluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(keluar);
        keluar.setBounds(40, 500, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Jenis Kendaraan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 300, 99, 15);

        buttonGroup1.add(mtr);
        mtr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mtr.setForeground(new java.awt.Color(204, 204, 204));
        mtr.setText("Motor");
        mtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtrActionPerformed(evt);
            }
        });
        getContentPane().add(mtr);
        mtr.setBounds(40, 320, 80, 30);

        buttonGroup1.add(mbl);
        mbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mbl.setForeground(new java.awt.Color(204, 204, 204));
        mbl.setText("Mobil");
        getContentPane().add(mbl);
        mbl.setBounds(140, 320, 80, 30);

        Save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(153, 0, 0));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(290, 310, 80, 31);

        Delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(153, 0, 0));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(490, 310, 90, 31);

        Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(153, 0, 0));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(390, 310, 80, 31);

        Refresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Refresh.setForeground(new java.awt.Color(153, 0, 0));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh);
        Refresh.setBounds(600, 310, 100, 31);

        Edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Edit.setForeground(new java.awt.Color(153, 0, 0));
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(720, 310, 80, 31);

        Print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Print.setForeground(new java.awt.Color(153, 0, 0));
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        getContentPane().add(Print);
        Print.setBounds(820, 310, 80, 31);

        tblData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblData.setForeground(new java.awt.Color(153, 0, 0));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NoResi", "Petugas", "JenisKendaraan", "NoPol", "TanggalMasuk", "TanggallKeluar", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(290, 390, 610, 140);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 160, 250, 390);

        hitung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hitung.setForeground(new java.awt.Color(153, 0, 0));
        hitung.setText("Hitung Hari");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(310, 180, 170, 30);

        harga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(harga);
        harga.setBounds(610, 230, 170, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Harga");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 230, 70, 30);

        lama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lama);
        lama.setBounds(310, 230, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Data Kendaraan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 130, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 110, 890, 40);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(280, 160, 630, 120);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(280, 290, 630, 70);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(280, 370, 630, 180);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("RAJAJOWAS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(670, 20, 210, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Penitipan Khusus Motor Dan Mobil");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 60, 260, 30);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 10, 890, 90);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 0, 930, 570);

        setBounds(0, 0, 945, 606);
    }// </editor-fold>//GEN-END:initComponents

    private void petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petugasActionPerformed

    private void mtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtrActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String klr = dateFormat.format(keluar.getDate());
        String msk = dateFormat.format(masuk.getDate());
        
        String JK = "";

        if (mtr.isSelected()) {
            JK = "Motor";
        } else {
            JK = "Mobil";
        }
        if ("".equals(resi.getText()) || 
                "".equals(petugas.getText()) || 
                JK.equals("") ||
                "".equals(nopol.getText()) || 
                msk.equals("") || 
                klr.equals("") ||
                "".equals(harga.getText()) )
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error",
                JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL ="INSERT INTO tb_penitipan VALUES"
                    + "('" +resi.getText()
                    +"','"+petugas.getText()
                    +"','"+JK+"',"+nopol.getText()+"','"+msk+"','"
            +klr+"','"
            + harga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal disimpan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            String Resi = tblData.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM tb_penitipan WHERE NoResi='"+Resi+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        resi.setText("");
        petugas.setText("");
        nopol.setText("");
        buttonGroup1.clearSelection();
        masuk.setDateFormatString("");
        keluar.setDateFormatString("");
        lama.setText("");
        harga.setText("");
        
        
    }//GEN-LAST:event_ClearActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_RefreshActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String klr = dateFormat.format(keluar.getDate());
        String msk = dateFormat.format(masuk.getDate());
        if ("".equals(petugas.getText()) ||
            "".equals(resi.getText()) ||
            "".equals(nopol.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String JK = "";
            if (mtr.isSelected()) {
                JK = "Motor";
            }else{
                JK = "Mobil";
            }
            String SQL = "UPDATE tb_penitipan SET "
            + "NoResi='"+resi.getText()+"',"
            + "NoKendaraan='"+nopol.getText()+"',"
            + "TanggalMasuk='"+msk+"',"
            + "TanggalKeluar='"+klr+"',"
            + "JenisKendaraan='"+JK+"',"
            + "WHERE Petugas='"+petugas.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_EditActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Penitipan Motor dan Mobil");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            resi.setText(tblData.getValueAt(baris, 0).toString());
            petugas.setText(tblData.getValueAt(baris, 1).toString());
            nopol.setText(tblData.getValueAt(baris, 3).toString());
            SimpleDateFormat date = new SimpleDateFormat ("yyyy-MM-dd");
            Date dateFormatmsk = null;
            Date dateFormatklr = null;
            try {
                dateFormatmsk = date.parse(tblData.getValueAt(baris, 4).toString());
                dateFormatklr = date.parse(tblData.getValueAt(baris, 5).toString());
            } catch (ParseException ex) {
                Logger.getLogger(Penitipan.class.getName()).log(Level.SEVERE, null, ex);
            }
            masuk.setDate(dateFormatmsk);
            keluar.setDate(dateFormatklr);

            if ("Motor".equals(tblData.getValueAt(baris, 2).toString())) {
                mtr.setSelected(true);
            } else {
                mbl.setSelected(true);
            }
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Date k = keluar.getDate();
        Date m = masuk.getDate();
        long startTime = m.getTime();
        long endTime = k.getTime();

        long titipTime = endTime - startTime;
        long hari = titipTime / (1000 * 60 * 60 * 24);
        DateFormat dateFormat = DateFormat.getDateInstance();

        lama.setText(" "+hari+" hari");

        int lm = toIntExact(hari);
        int total = lm * 3000;
        String hrg = Integer.toString(total);

        harga.setText(hrg);

    }//GEN-LAST:event_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penitipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penitipan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Print;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser keluar;
    private javax.swing.JTextField lama;
    private com.toedter.calendar.JDateChooser masuk;
    private javax.swing.JRadioButton mbl;
    private javax.swing.JRadioButton mtr;
    private javax.swing.JTextField nopol;
    private javax.swing.JTextField petugas;
    private javax.swing.JTextField resi;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
